apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-ingress-dns
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-ingress-dns
  template:
    metadata:
      labels:
        app: kubernetes-ingress-dns
    spec:
      serviceAccountName: kubernetes-ingress-dns-controller
      containers:
        - name: kubernetes-ingress-dns
          image: ghcr.io/dustinrouillard/kubernetes-ingress-dns
          env:
            - name: INGRESS_SERVICE_NAMESPACE
              value: traefik
            - name: INGRESS_SERVICE_NAME
              value: traefik
          ports:
            - containerPort: 53
              protocol: UDP
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
